# Generated by Django 5.1.1 on 2024-10-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='instrument',
            new_name='instrument_rating',
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
