# Generated by Django 5.1.3 on 2024-12-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_rename_instrument_album_instrument_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='instrument_rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10),
        ),
    ]
