# Generated by Django 5.1.1 on 2024-10-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicmodel',
            old_name='instrument',
            new_name='instrument_type',
        ),
    ]
